### ISSUE TITLE
Question stats not working 

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/socli#179]
Question voting stats not working

**Comment by therajdeepbiswas** [comment]
Would like to contribute. More details please?

**Comment by hedythedev** [comment]
![Screen shot from @tranchikhang in pr #174 ](https://user-images.githubusercontent.com/16659747/72485946-bc893500-384c-11ea-9090-a652ba905598.PNG)

It shows ‘could not load statistics’ when a question and answer is displayed. To my knowledge, what it should show is the voting stats, and the date that the question is created.

I think, you can have a look into [L110 to 146 of search.py](https://github.com/gautamkrishnar/socli/blob/master/socli/search.py#L110L146)

Or more specifically, the [`get_stats` method in socli/search.py](https://github.com/gautamkrishnar/socli/blob/master/socli/search.py#L128L146) the problem seems to be happening there.

**Comment by hedythedev** [comment]
Hi @gautamkrishnar I have just taken a look at the stack overflow site source, and I think they changed their class names and HTML structure like the case for issue #163 
So, because there was no `div` with class name `module question-stats`, the logic in `search.py` on line won’t find anything, which causes an index error exception, leading to a message `could not load statistics` being shown.
I think the solution for this would be find out what class is for the voting stats, and then change the logic on that line to find the correct info.

**Comment by therajdeepbiswas** [comment]
Hey @hedythedev, the HTML structure has indeed changed, we do not get the questions-stats as conveniently anymore as it was being done before. Although I managed to get the functionality back as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/32306614/84235221-1a2b6000-ab13-11ea-8270-8ea0bdd5d20d.png)

But I am a bit apprehensive about the way I'm having to fetch view counts. The previous vote counter can still be used, the time of question posted and last activity are reliant on a <time> tag and an <a> tag, respectively, however, the view count has to rely on a css class. (`class_="grid--cell ws-nowrap mb8"`).

I will raise a PR nonetheless, please review.

**Comment by gautamkrishnar** [comment]
@therajdeepbiswas @hedythedev thanks a lot for digging into this 😄
