### ISSUE TITLE
Issue with code changes moving across fork branches.

### ISSUE THREAD

**Issue by therajdeepbiswas** [gautamkrishnar/socli#184]
I faced this problem working on my fork of this repository. When I would make changes to some file(s) and then switch to a different branch, git will not raise the `error: You have local changes to "X"; cannot switch branches.` error. Instead it will just move to the new branch **and** reflect the changes in that branch as well. Please let me know if this a beginner mistake on my part.

Steps to reproduce -
1. Fork the repository
2. `git remote add upstream git@github.com:gautamkrishnar/socli.git`
3. `git fetch upstream`
4. `git merge upstream/master`
5. `git checkout -b new-branch-name`
6. Make changes to any file
7. Switch back to master and those changes would reflect there

This is causing my master to be the same as a branch that I made changes to, which continued to stay after. Committing, however fixes this issue.

**Comment by hedythedev** [comment]
Yes, that happens when you switch branches and have uncommitted work. If you change some files on branch A, then checkout branch B the changes on branch A will still be shown. So if you don't have push access to the branch you are switching to, always commit the changes before switching to another branch. Unless of course if you need the changes to be on the branch you're switching to.
