### ISSUE TITLE
Why is socli not using stackexchange's API

### ISSUE THREAD

**Issue by danidee10** [gautamkrishnar/socli#19]
I just came across this project this evening (GMT + 1) and i'm really interested in it (I've already given it a star)

I've gone through the code a little, and i discovered that socli uses beautifulSoup to scrape stackoverflow directly.

Wouldn't it be better and safer (because stackoverflow might decide to change their markup anytime) to use the official [API](https://api.stackexchange.com/docs)?

If this is a planned feature...i'll be glad to contribute in anyway to see a re-implementation with the official API.

**Comment by gautamkrishnar** [comment]
Yes we can use the api. I am also planning to use the api to add more interactivity to socli, so that you can add,  delete,  up vote etc using the command line interface.  

I used beautifulsoup to make the searching process simpler.  Yes if stackoverflow.com changes their markup then it won't work. Really  Happy to hear that you are willing to contribute to this project :smiley:
